/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 clay.glb --types -k --shadows --transform
Files: clay.glb [13.13KB] > /Users/andrea/Documents/models/clay-transformed.glb [2.26KB] (83%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Mesh_sand_rocks: THREE.Mesh;
    Mesh_sand_rocks_1: THREE.Mesh;
  };
  materials: {
    dirt: THREE.MeshStandardMaterial;
    sand: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Clay3DTile(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/clay-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Mesh_sand_rocks"
        castShadow
        receiveShadow
        geometry={nodes.Mesh_sand_rocks.geometry}
        material={materials.dirt}
      />
      <mesh
        name="Mesh_sand_rocks_1"
        castShadow
        receiveShadow
        geometry={nodes.Mesh_sand_rocks_1.geometry}
        material={materials.sand}
      />
    </group>
  );
}

useGLTF.preload('/models/clay-transformed.glb');
