/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robbers.glb --types -k --shadows --transform
Files: robbers.glb [2.94KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/robbers-transformed.glb [1.24KB] (58%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    dirt: THREE.Mesh;
  };
  materials: {
    dirt: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Robbers3DTile(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/robbers-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="dirt"
        castShadow
        receiveShadow
        geometry={nodes.dirt.geometry}
        material={materials.dirt}
      />
    </group>
  );
}

useGLTF.preload('/models/robbers-transformed.glb');
