/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_9.glb --types -k --shadows --transform
Files: num_9.glb [260.34KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_9-transformed.glb [26.62KB] (90%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text006: THREE.Mesh;
  };
  materials: {
    ['materiale.006']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_9.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text006"
        castShadow
        receiveShadow
        geometry={nodes.Text006.geometry}
        material={materials['materiale.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_9.glb');
