/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_2.glb --types -k --shadows --transform
Files: num_2.glb [872.18KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_2-transformed.glb [76.75KB] (91%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh;
    Text001: THREE.Mesh;
    Text004: THREE.Mesh;
  };
  materials: {
    materiale: THREE.MeshStandardMaterial;
    ['materiale.001']: THREE.MeshStandardMaterial;
    ['materiale.004']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Num_2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_2.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text"
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.materiale}
        position={[0.022, -0.122, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_2.glb');
