/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_11.glb --types -k --shadows --transform
Files: num_11.glb [79.09KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_11-transformed.glb [10.45KB] (87%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text008: THREE.Mesh;
    Text009: THREE.Mesh;
  };
  materials: {
    ['materiale.009']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Num_11(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_11.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text008"
        castShadow
        receiveShadow
        geometry={nodes.Text008.geometry}
        material={nodes.Text008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_11.glb');
