/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_5.glb --types -k --shadows --transform
Files: num_5.glb [565.62KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_5-transformed.glb [59.11KB] (90%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text003: THREE.Mesh;
    Text004: THREE.Mesh;
    Text006: THREE.Mesh;
  };
  materials: {
    ['materiale.004']: THREE.MeshStandardMaterial;
    ['materiale.006']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Num_5(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_5.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text003"
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={nodes.Text003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_5.glb');
