/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_8.glb --types -k --shadows --transform
Files: num_8.glb [409.64KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_8-transformed.glb [43.59KB] (89%)
*/

import * as THREE from 'three';
import React, { useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text005: THREE.Mesh;
    Text006: THREE.Mesh;
  };
  materials: {
    ['materiale.006']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Num_8(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_8.glb'
  ) as GLTFResult;

  useEffect(() => {
    // Modify the existing material's color
    (nodes.Text005.material as THREE.MeshStandardMaterial).color.set('coral');
  }, [nodes.Text005.material]);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text005"
        castShadow
        receiveShadow
        geometry={nodes.Text005.geometry}
        material={nodes.Text005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_8.glb');
