/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_12.glb --types -k --shadows --transform
Files: num_12.glb [71.82KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_12-transformed.glb [9.11KB] (87%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text009: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

export function Num_12(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_12.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text009"
        castShadow
        receiveShadow
        geometry={nodes.Text009.geometry}
        material={nodes.Text009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_12.glb');
