/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_3.glb --types -k --shadows --transform
Files: num_3.glb [691.48KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_3-transformed.glb [71.56KB] (90%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text001: THREE.Mesh;
    Text002: THREE.Mesh;
    Text004: THREE.Mesh;
  };
  materials: {
    ['materiale.002']: THREE.MeshStandardMaterial;
    ['materiale.004']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_3.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text001"
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Text002"
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials['materiale.002']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Text004"
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={materials['materiale.004']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_3.glb');
