/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 num_6.glb --types -k --shadows --transform
Files: num_6.glb [504.6KB] > /Users/andrea/Desktop/settlers/packages/frontend/public/models/numbers/num_6-transformed.glb [53.84KB] (89%)
*/

import * as THREE from 'three';
import React, { useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text004: THREE.Mesh;
    Text005: THREE.Mesh;
    Text006: THREE.Mesh;
  };
  materials: {
    ['materiale.005']: THREE.MeshStandardMaterial;
    ['materiale.006']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Num_6(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/numbers/num_6.glb'
  ) as GLTFResult;

  useEffect(() => {
    // Modify the existing material's color
    (nodes.Text004.material as THREE.MeshStandardMaterial).color.set('coral');
  }, [nodes.Text004.material]);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Text004"
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={nodes.Text004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/numbers/num_6.glb');
